VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Definition"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule VariableNotUsed
'@Folder "PearPMProject.src.Config.Definition"
Option Explicit

Public Key As String
Public Short As String
Public DataType As VbVarType
Public Default As Variant
Public Description As String
